# Same as reported in matthews et al. Craftax paper
NAME_INITIALS: "RE"
TOTAL_TIMESTEPS: 1e9
NUM_ENVS: 1024
NUM_STEPS: 64
ALG_NAME: "PPO"
LR: 2.5e-4
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 8
GAMMA: 0.99
GAE_LAMBDA: 0.8
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "relu"
ANNEAL_LR: True
WANDB_MODE: "online"
ENTITY: ""
PROJECT: "NEXUS_rebuttal2"

ENV_NAME: "Craftax-Classic-Symbolic-v1"
ENV_KWARGS: {}
USE_OPTIMISTIC_RESETS: True
OPTIMISTIC_RESET_RATIO: 16
LOG_ACHIEVEMENTS: False

TEST_INTERVAL: 10000
TEST_NUM_ENVS: 1024
TEST_NUM_STEPS: 10000
RECORD_VIDEO: True