NAME_INITIALS: "RE"
TOTAL_TIMESTEPS: 5e7
NUM_ENVS: 128
NUM_STEPS: 128
ALG_NAME: "PPO_noisy0"
LR: 2.5e-4
UPDATE_EPOCHS: 2
NUM_MINIBATCHES: 64
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "relu"
ANNEAL_LR: True
WANDB_MODE: "online"
ENTITY: ""
PROJECT: "LENS"
ENV_NAME: "Kangaroo"
STICKY_ACTIONS: False
EPISODIC_LIFE: False

TEST_INTERVAL: 10000
TEST_NUM_ENVS: 128
TEST_NUM_STEPS: 10000
RECORD_VIDEO: True

# noise
NOISY_TRAINING: True
NOISY_EVAL: True
DETECT_PROB: 0.9
NOISE_STD_DEV: 3.0