NUM_SEEDS: 1
# this is adapted from Atari configuration 
NAME_INITIALS: "RE"
ALG_NAME: "pqn_hier_llm"
NUM_ENVS: 1024 # parallel environments
NUM_STEPS: 10000 #number of steps per env
NORM_TYPE: "layer_norm" # layer_norm or batch_norm
NORM_INPUT: False 
LR: 1.0e-4
MAX_GRAD_NORM: 10
LR_LINEAR_DECAY: False
GAMMA: 0.99
LAMBDA: 0.65
HIDDEN_SIZE: 64
NUM_LAYERS: 3

# env specific
ENV_NAME: "Pong"
ENV_KWARGS: {}

LOAD_PATH: "/home/remunds/projects/symbolic_options/models/"